name: GitHub project test
run-name: ${{ github.actor }} is testing 🚀
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Check-out-Git-repository:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup PHP with phpcs extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          coverage: none
          tools: phpcs, phpunit
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          php_codesniffer: true
